### ISSUE TITLE
ESP32 A2DP_source_demo and headset with 0x200404 class

### ISSUE THREAD

**Issue by b4b4k** [bluekitchen/btstack#131]
hi
i want to connect to the my [headset](https://www.gearbest.com/earbud-headphones/pp_757978.html) and use it as walkie talkie but i get this...
![image](https://user-images.githubusercontent.com/30823073/40423384-a509cc4e-5ea7-11e8-8ca4-07aa88a401d0.png)

i uncomment the  #undef  HAVE_BTSTACK_STDIN  to auto connect
and my headset class code is: 0x200404

**Comment by mringwal** [comment]
If possible, please post on the btstack dev mailing list. http://groups.google.com/group/btstack-dev
You may also copy & paste text instead of images (makes it better to read).

For walkie-talkie (using the mic of the headset), A2DP cannot be used. You'd need to use HSP or HFP profile. Both profiles use SCO. SCO hasn't been supported on ESP32 until yesterday: https://github.com/espressif/esp-idf/issues/1118#issuecomment-390904865

We will look into supporting SCO (and with this HSP/HFP) soonish.
