### ISSUE TITLE
Byte Order format support

### ISSUE THREAD

**Issue by jhpark555** [bluekitchen/btstack#137]
I'm trying to port BTstack on OpenRISC cpu.  The OpenRISC uses Big endian data format. Does this stack support the big endian format?  I couldn't see the configuration about byte order definition.

Thanks,

**Comment by mringwal** [comment]
hi. BTstack works correctly on big endian and little endian. Instead of doing a cast to the required data size (e.g. uint32_t) and then swapping the bytes if there's a difference between the data format and the host architecture, BTstack has helper functions that read/store values byte by byte. This may be slower, but it's always correct. (see the little_endian_* and big_endian_* in src/btstack_util.h).
