### ISSUE TITLE
Simultaneous Profile Restrictions?

### ISSUE THREAD

**Issue by AGlass0fMilk** [bluekitchen/btstack#142]
Hi!

I am looking into using this stack for a project requiring simultaneous A2DP source **and** sink, AVRCP, HFP, and BLE. 

The data transmission over BLE will be pretty light.
I'm looking into using the STM32F4 coupled with a CC2564. Can someone comment on simultaneous profile restrictions or caveats I may encounter?

I look forward to playing around with this library when I get the CC2564 dev kit :)

**Comment by mringwal** [comment]
Hi George. For community feedback etc. please post on the mailing list (http://groups.google.com/group/btstack-dev), I don't think anybody browses the issue tracker. 

In general, there are no restrictions for using multiple profiles by design. In the implementation, some protocols might use a single context. A2DP Sink and Source works and if you're just forward the audio, you might skip the SBC decoding/encoding step.

Please check btstack_config.h to see if your configuration is supported (enough HCI, L2CAP, AVDTP channels, etc..)

For commercial projects, please get in touch at contact@bluekitchen-gmbh.com.
