### ISSUE TITLE
Add consumer HID report to HOG keyboard

### ISSUE THREAD

**Issue by darkyline** [bluekitchen/btstack#168]
Hello,

I am trying to use media keys on the keyboard, I did some research and saw the format of the HID report of consumer usage is different than the keyboard usage. I wonder can I add the possibility to add this use since I can't add it to the existing HOG example by adding to the HID descriptor.

Thanks.

**Comment by mringwal** [comment]
Hi. To use media keys, you'd need to modify/extend the HID descriptor to change the format of the HID Report and allows you to send consumer usages. (yes, HID is not intuitive and tricky to debug as nothing happens if something is incorrect). My recommendation is to start with a working HID descriptor and make the tiniest change you can think of and then verify that. Then Repeat until done.

Please post general developer question on the BTstack mailing list.
