### ISSUE TITLE
stack random freeze when waiting on ATT_EVENT_CAN_SEND_NOW

### ISSUE THREAD

**Issue by Lefix2** [bluekitchen/btstack#191]
Hi,
We are facing a problem without any idea of how to solve it.
We are using the stack in LE mode (all CLASSIC features disabled).
In some cases, we have to send some data (about 2k) in packets of ~280 bytes.

We are using FreeRTOS, so, on `sndtimer_handler` we check for received message in a queue and send `att_server_request_can_send_now_event()` to wait for the stack to be ready.

It frequently happens that the `ATT_EVENT_CAN_SEND_NOW` packet is never received.
After that, no write, read or connection is possible.

We tried to enable HCI dump to get more information, but in this case the bug disappeared.

Perhaps you've already faced this problem or you have an idea to explore?

**Comment by mringwal** [comment]
Hi

some random ideas..

do you call BTstack AP and att_server_request_can_send_now_event only from a single thread?

BTstack's free rtos run loop can either use FreeRTOS Notifications or EventGroups. We have a report Task Notifications might not be reliable in all conditions. If you're using Task Notifications, please try using Event Groups.

As you're saying nothing happens after waiting for ATT_EVENT_CAN_SEND_NOW, please check if the stack is running. a disconnect should get reported.

For HCI logging, instead of logging via UART, SEGGER RTT can be used. In addition to textual output, when selecting packetlogger mode, the HCI log is sent in binary via the channel #1. Due to it's design this logging often does not modify the behaviour.

good luck and please let me know if you are able to identify the problem

**Comment by Lefix2** [comment]
- Yes, all BT calls are made from a single thread.
- We are using message queue to communicate from a thread to another, and we don't wait on acquire. At each call to '`sndtimer_handler` we try to get a message, then leave or process it (with a call to 'att_server_request_can_send_now_event()')

- I've already noticed that a disconnect is reported.

- We'll manage to get a J-Link working. Actually we're using ST-Link that are not compatible with it (it appears)
We have a saleae logic analyzer to watch uart's exchange

Thanks for your help, i'll come back to you with news (if i have)!

**Comment by mringwal** [comment]
hi. any news/progress from your side?

**Comment by Lefix2** [comment]
Hi,
Yes, we managed to get a J-Link RTT link with our device.
It seems that the bug don't appear with HCI dump enabled again.
We think that the simple fact of processing a printf inside HCI exchanges generate a sufficient delay to prevent the bug from happening.
Is it possible that a bad configuration of the CC2564B can brick it when large amount of data is exchanged?

**Comment by Lefix2** [comment]
So, we managed to get HCI "dump" by spying lines with logic analyzer, you can find the formatted data at the following address:
[Link to file](https://cloud.onewave.fr/index.php/s/CzxPG9cZ2FGZpc6)
As you can see in this document, the freeze occurs at line 6165 with a missing ACL packet

We have some questions for now:
- Why all data we receive in ACL packets is sent again to CC2564B? Is it a BLE "rule"?
- Is it BTStack fault, since the first missing frame is an Tx frame?
- Is it possible to restart BTStack? We would like to temporarily cut/redo connection when a freeze happens, but we don't find any easy way to stop the main loop and re-init BTStack.

**Comment by mringwal** [comment]
Thanks for the binary dump with the logic analyzer. If you like, you could try to use https://github.com/bluekitchen/bluetooth-logger to convert UART traces to .pklg.
(Implemented for Salea Logic, but others should be similar).

In BLE, the data of a Prepared Write Request is sent back as Prepared Write Response, otherwise not. (It looks like your using this, probably for a Write Long Characteristic).

Restarting BTstack is possible, but only in "good standing" - you can call hci_power_control(off) to allow to fully turn of the Bluetooth Controller to save energy. It is not intended to make it recover from errors (although it might work in some cases).

At the time of the 'freeze', you get two HCI Num Completed Packets, which would allow to send another packet. I've got an educated guess: you're using DMA on an STM32 and use the STM32 Cube HAL, which has race conditions when using RX and TX at the same time....

I've run into a similar issue in the F4 Discovery port this week. The SET_BIT/CLEAR_BIT macros do a read-modify-write. If they are called from normal context, it could cause a write from IRQ to get overwritten.

Please compare this to your code and update it accordingly: https://github.com/bluekitchen/btstack/commit/82af58d38d542c492f920a9742d749f2ba67b036

In addition, make sure that the DMA Irqs for UART RX and TX have the same pre-emption priority

**Comment by Lefix2** [comment]
Thanks for your tool it will be usefull!
Perhaps you should indicate in README that baudrate has to be changed in python file!?

And thanks a lot for your bugfix, it seem to be the root of our problem (we are sending kB of data since 30 min without a bug).
Have you reported this issue to ST yet?

**Comment by mringwal** [comment]
Thanks for the comment on setting the baudrate in the salea logic tool. I've set it to 11520 and updated the README.

I wouldn't mind reporting this to ST, but don't have a direct contact and could not find a bug tracker - I only found the community forum. Any ideas how to report properly?

**Comment by Lefix2** [comment]
The problem with this critical section is if this function is called inside an other critical section it will re-enable irqs...
Perhaps community forums is a good entry-point, we have some contact at ST we can search this way.

**Comment by mringwal** [comment]
hi. that's correct. It would be better/more general, if the interrupt enable bit would be stored and restored after the critical section. With BTstack, it's never called from IRQ context, so that's good enough for me.

However, the F4 has support for bit-banding, which would allow to set/clear bits without disabling interrupts. That would be the correct solution by the way (but I didn't try bit-banding before, and i would be some work to update the whole HAL ).
