### ISSUE TITLE
SM compatible

### ISSUE THREAD

**Issue by Tsai1005** [bluekitchen/btstack#311]
In the SM profile, there is a default setting about IR & ER
![image](https://user-images.githubusercontent.com/17000928/89883834-4c346d80-dbfb-11ea-96be-d44d3c02203c.png)

**Comment by mringwal** [comment]
Hi. Could you explain this issue? What did you do? What did you expect? What happened? 
Which side sends the SMP Pairing Failed?

**Comment by mringwal** [comment]
btw. it looks like one side is the popular CSR 4.0 dongle, so you're probably on a desktop system. Please also post the /tmp/hci_dump.pklg and or hci_dump.pklg (on windows in local folder).

**Comment by Tsai1005** [comment]
Our device is acting as a slave, then connect to the PC, but found that some tablets will terminate the connection after the SM key distribution process, but the situation will change after we modify the IR key.

[keyboard_pc.zip](https://github.com/bluekitchen/btstack/files/5056637/keyboard_pc.zip)

**Comment by Tsai1005** [comment]
In my opinion the problem would related to the LTK, it derives from the IR.
![LE Security](https://user-images.githubusercontent.com/17000928/89892149-d505d600-dc08-11ea-8ef6-3bac4392bccd.jpg)

**Comment by mringwal** [comment]
What tool do I need to open the keyboard_pc.btt file in the .zip above?

Do you use random bluetooth addresses?
Can you provide btstack's packet log?

The IR and ER should be unique for each device - otherwise, there are issues with using private addresses and also security implications. There's a chance, your table has the IRK derived from  the fixed IR black-listed (I haven't heard about that, but it's quite possible)

In the current version, BTstack will generate random numbers for IR + ER and store it in it's TLV data base (which should be in Flash). If that's working, each device will have unique IR + ER values and the tablet should have no problems with that.

Do you have TLV properly setup such that it can be used by BTstack?
