### ISSUE TITLE
hid_host.h: hid_descriptor_storage_get_descriptor_len: type qualifiers ignored on function return type

### ISSUE THREAD

**Issue by ecc1** [bluekitchen/btstack#355]
Using ESP-IDF v4.2 (Docker image) with gcc 8.4.0, btstack v1.2-326-g924daf9e4

This warning is printed for every file that includes hid_host.h:

`/opt/esp/idf/components/btstack/src/classic/hid_host.h:269:1: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
 const uint16_t hid_descriptor_storage_get_descriptor_len(uint16_t hid_cid);`

**Comment by mringwal** [comment]
Hi Eric. Thanks for reporting. It looks like we've stumbled upon this ourselves as it was fixed in https://github.com/bluekitchen/btstack/commit/2cfd07fa7ffab8635d954b8a7e7720bdfa68ccad

It will be on the next master release, v1.4, probably in towards the end of May.
(or just drop the const in .h and .c for now).
