### ISSUE TITLE
Implementation of "Passkey Entry" pairing methode for classic bluetooth 

### ISSUE THREAD

**Issue by AlexanderSveshnikov** [bluekitchen/btstack#376]
Hello 
I'm trying to implement "Passkey Entry" pairing  method using Bluekitchen Stack for classic bluetooth (2.1). I'm using ESP32 (but I think it doesn't matter for my question). The only mention about this pairing method in  BTstack Manual (master-51ddac10e July 20, 2021) related with Bluetooth LE (on page 50, "User interaction during Pairing"). Is it usable for Classic Bluetooth?
And I can't find  "Passkey Entry" pairing example. Please give me some advises that helps me with  
"Passkey Entry" pairing  implementation.

**Comment by mringwal** [comment]
Please post general questions like this on the mailing list.

To configure Secure Simple Pairing (SSP), you can use the gap_ssp_x functions defined in src/gap.h. Passkey Entry will provide Security Level 3, so you need to configure the stack to use LEVEL_3 as well (otherwise, Just Works pairing will be used)

If you call:
- gap_set_security_level(LEVEL_3) and also use LEVEL_3 for outgoing connections, if security level can be specified
- gap_ssp_set_io_capability(SSP_IO_CAPABILITY_KEYBOARD_ONLY)

you should end up with PassKey Entry. You can make these changes to spp_streamer and spp_streamer_client for example.
