### ISSUE TITLE
How to debug with .launch file in eclipse?

### ISSUE THREAD

**Issue by Yanjiong** [bluekitchen/btstack#78]
Hi,

For the steps "start it via the provided Debug Launch configuration "example-debug"", how to do that in current eclipse?

Thanks.

BR.

**Comment by mringwal** [comment]
Do you refer to the STM32F4 Discovery port features in our blog?
What Eclipse do you have and what changed?

**Comment by Yanjiong** [comment]
Yes, stm32-f4discovery-cc256x port examples.
Eclipse is Neon.3 Release.

Thanks.

**Comment by mringwal** [comment]
I've used Neon.3 Release while writing the blog post.
If you click on the little triangle next to the "Debug" button, a list with debug launch configurations show up, like here:

![screen shot 2017-09-27 at 10 02 57](https://user-images.githubusercontent.com/652934/30902334-2a2da038-a36b-11e7-9510-ffa413ebe9ef.png)

Does this help?

**Comment by Yanjiong** [comment]
no debug menu on my view...

![screenshot from 2017-09-27 16-33-55](https://user-images.githubusercontent.com/1078207/30903553-c413c3ae-a3a1-11e7-802f-a8a1a29a7822.png)

Is it needed to add it in some way?

**Comment by mringwal** [comment]
That's weird. The debug config is the file 'spp_counter-debug.launch' seen in your project explorer. I didn't use Eclipse before or after this port and I remember that the debug configs did show up twice before (not so bad, just not tidy).

As an alternative, you could flash the compiled .elf with openocd or the st-link tool. See the other STM32 examples.

**Comment by Yanjiong** [comment]
Is there any instruction about how to develop btstack at STM32f4discovery+CC256X in command line mode under ubuntu?

**Comment by mringwal** [comment]
I don't have anything written. The STM32F4Discovery has an ST-Link programming adapter. You can either use the st-link tool (https://github.com/texane/stlink) or OpenOCD (http://openocd.org) to download firmware and/or debug. Please google for tutorials on this.

In general, I usually just download the firmware and use log_info statements together with the packet logging, since pausing the program in the debugger often causes Bluetooth timeouts.
